version: '3.9'
services:
  postgres-data:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow_data
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  airflow-init:
    image: apache/airflow:2.10.2
    depends_on:
      - postgres-data
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres-data:5432/airflow_data
    entrypoint: /bin/bash
    command: -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"

  airflow-webserver:
    image: apache/airflow:2.10.2
    restart: always
    depends_on:
      - postgres-data
      - airflow-init
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres-data:5432/airflow_data
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.10.2
    restart: always
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres-data:5432/airflow_data
    command: scheduler

  redis:
    image: redis:7


  irflow-worker:
    image: apache/airflow:2.10.2
    restart: always
    depends_on:
      - airflow-init
      - redis
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres-data:5432/airflow_data
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres-data:5432/airflow_data
    command: ["airflow", "celery", "worker"]

  fastapi:
    build: ./api
    container_name: fastapi
    environment:
      - DATABASE_URL=postgresql://airflow:airflow@postgres-data/airflow_data
    ports:
      - "8000:8000"
    depends_on:
      - postgres-data

volumes:
  postgres_data: