version: '3.9'

x-airflow-common-env: &airflow-common-env
  AIRFLOW__CORE__EXECUTOR: CeleryExecutor
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-data:5432/airflow_data
  AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
  AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres-data:5432/airflow_data
  AIRFLOW__CORE__FERNET_KEY: FfPmp2RvhD6gM1q3gD5I5X9aOYF4F5b6hS6hTgW0sMg=
  AIRFLOW__WEBSERVER__SECRET_KEY: super_secret_shared_key_123
  AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
  AIRFLOW__LOGGING__LOGGING_LEVEL: INFO
  AIRFLOW__LOGGING__REMOTE_LOGGING: False

services:
  postgres-data:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow_data
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default

  redis:
    image: redis:7
    networks:
      - default

  airflow-init:
    build:
      context: ./airflow
    networks:
      - default
    depends_on:
      - postgres-data
    environment:
      <<: *airflow-common-env
    env_file:
      - .env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
    entrypoint: /bin/bash
    command: -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"

  airflow-webserver:
    build:
      context: ./airflow
    restart: always
    networks:
      - default
    depends_on:
      - airflow-init
    environment:
      <<: *airflow-common-env
    env_file:
      - .env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    build:
      context: ./airflow
    restart: always
    networks:
      - default
    depends_on:
      - airflow-init
    env_file:
      - .env
    environment:
      <<: *airflow-common-env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
    command: scheduler

  airflow-worker:
    build:
      context: ./airflow
    restart: always
    networks:
      - default
    depends_on:
      - airflow-init
      - redis
    env_file:
      - .env
    environment:
      <<: *airflow-common-env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
    command: ["airflow", "celery", "worker"]

  fastapi:
    build: ./api
    container_name: fastapi
    environment:
      - DATABASE_URL=postgresql://airflow:airflow@postgres-data:5432/airflow_data
    ports:
      - "8000:8000"
    depends_on:
      - postgres-data
    networks:
      - default



volumes:
  postgres_data:

networks:
  default:
    driver: bridge