tickers:
  - GAZP.ME   # Газпром
  - SBER.ME   # Сбербанк
  - LKOH.ME   # Лукойл
  - GMKN.ME   # Норильский никель
  - NVTK.ME   # Новатэк
  - BTC-USD   # Биткоин
  - ETH-USD   # Эфириум

settings:
  start: "2015-01-01"
  end: "2025-10-01"
  interval: "1d"
  save_to: "quotes.csv"
